# Generated by Django 4.2.4 on 2023-11-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_user_referal_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referal_money',
        ),
    ]
