# Generated by Django 4.2.4 on 2023-11-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('region', models.PositiveIntegerField()),
                ('organizations', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('region', models.PositiveIntegerField()),
                ('organizations', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
            ],
        ),
    ]
