# Generated by Django 4.2.4 on 2023-11-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='reject',
            field=models.BooleanField(default=True),
        ),
    ]
