# Generated by Django 4.2.4 on 2023-11-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tempuser_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
